### ISSUE TITLE
 500 error

### ISSUE THREAD

**Issue by ur662255** [arnia/Karybu#12]
Hello

After the installation Karybu cms 500 error.

It is impossible progression Any more.

**Comment by dragan-dan** [comment]
what version have installed? can you access admin link (yourwebsite.com/admin)?

**Comment by ur662255** [comment]
stable version is l

http://karybu.org/getting-started.html

**Comment by dragan-dan** [comment]
and can you access admin link?

**Comment by ur662255** [comment]
Let's give it a try.

Thank you

**Comment by ur662255** [comment]
I xe-core users Korea 

However, Korea has many errors xe core 

  Participated in a project to try to use just saying Karybu.

There are many users Korea xe core.

**Comment by dragan-dan** [comment]
i understand, please let me know if you need any more help

**Comment by ur662255** [comment]
Thank you
